version: '3.7'

services:
  client-mainnet:
    image: nakachain/client-mainnet:v1.5.0
    build:
      context: ../../../
      dockerfile: ./docker/dockerfiles/Dockerfile.client
      args:
        GENESIS_PATH: ./metadata/mainnet/genesis.json
        STATIC_NODES_PATH: ./metadata/mainnet/static-nodes.json
        EXPOSED_PORTS: "8545 8546 30303"
        CHAIN_ID: ${CHAIN_ID}
        BOOTNODES: ${BOOTNODES}
        LISTEN_PORT: ${LISTEN_PORT}
        RPC_PORT: ${RPC_PORT}
        WS_PORT: ${WS_PORT}
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        failure_action: rollback
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - ${HOST_DATA_DIR}:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-size: "400m"
        max-file: "10"
