version: '3.7'

services:
  testnet-node1:
    hostname: testnet-node1
    container_name: testnet-node1
    build:
      context: .
      dockerfile: ./docker/init/Dockerfile
    volumes:
      - ~/.naka/node1:~/.naka
      - ./setup/genesis.json:~/.naka/genesis.json

  testnet-node2:
    hostname: testnet-node2
    container_name: testnet-node2
    build:
      context: .
      dockerfile: ./docker/init/Dockerfile
    volumes:
      - ~/.naka/node2:~/.naka
      - ./setup/genesis.json:~/.naka/genesis.json
