version: '3.7'

services:
  testnet-node1:
    hostname: testnet-node1
    container_name: testnet-node1
    build:
      context: .
      dockerfile: ./docker/init/Dockerfile
    volumes:
      - node1-testnet-data:/root/.naka:rw
      - ./setup/genesis.json:/root/.naka/genesis.json:ro

  testnet-node2:
    hostname: testnet-node2
    container_name: testnet-node2
    build:
      context: .
      dockerfile: ./docker/init/Dockerfile
    volumes:
      - node2-testnet-data:/root/.naka:rw
      - ./setup/genesis.json:/root/.naka/genesis.json:ro

volumes:
  node1-testnet-data:
  node2-testnet-data: