version: '3.7'

services:
  naka-testnet-node1:
    container_name: naka-testnet-node1
    image: nakachain/go-naka
    volumes:
      - ~/.naka/node1:/root/.ethereum/
      - ./setup/genesis.json:/root/.naka/genesis.json:ro
    command: --identity "naka-testnet-node1" init /root/.naka/genesis.json

  naka-testnet-node2:
    container_name: naka-testnet-node2
    image: nakachain/go-naka
    volumes:
      - ~/.naka/node2:/root/.ethereum/
      - ./setup/genesis.json:/root/.naka/genesis.json:ro
    command: --identity "naka-testnet-node2" init /root/.naka/genesis.json
