version: '3.7'

services:
  bootnode:
    container_name: naka-bootnode
    image: nakachain/bootnode
    volumes:
      - ~/.naka/boot.key:/root/.naka/boot.key:ro
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101
    ports:
      - 30301:30301/udp
    security_opt:
      - apparmor:unconfined
    command: -nodekey /root/.naka/boot.key -verbosity 9

  naka-testnet-node1:
    depends_on:
      - bootnode
    container_name: naka-testnet-node1
    image: nakachain/go-naka
    volumes:
      - ~/.naka/node1:/root/.ethereum/
      - ./setup/genesis.json:/root/.naka/genesis.json:ro
      - ./setup/keystore:/root/.ethereum/keystore:rw
      - ./setup/password.txt:/root/.naka/password.txt:ro
    networks:
      chainnet: 
        ipv4_address: 172.25.0.102
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
    security_opt:
      - apparmor:unconfined
    command: --syncmode "full" --networkid "25" --targetgaslimit "4700000" --port 30303 --rpc --rpcport 8545 --rpcaddr "0.0.0.0" --rpccorsdomain "*" --nat=none --verbosity=4 --mine --bootnodes "enode://be18154ff3753dbb46d59efa460d708a8eec1b547a2983b82ab36a50716e547ed0ca56f97ef625e469b2b752f3db07e1d85952bf87ba328f947a88613ffce755@172.25.0.101:30301" --etherbase "0x8102c0ecece895b8fefbddf42b95b7a20925b0c8" --unlock "0x8102c0ecece895b8fefbddf42b95b7a20925b0c8" --password "/root/.naka/password.txt"

  naka-testnet-node2:
    depends_on:
      - bootnode
    container_name: naka-testnet-node2
    image: nakachain/go-naka
    volumes:
      - ~/.naka/node2:/root/.ethereum/
      - ./setup/genesis.json:/root/.naka/genesis.json:ro
      - ./setup/keystore:/root/.ethereum/keystore:rw
      - ./setup/password.txt:/root/.naka/password.txt:ro
    networks:
      chainnet: 
        ipv4_address: 172.25.0.103
    ports:
      - 8546:8545
      - 30304:30303
      - 30304:30303/udp
    security_opt:
      - apparmor:unconfined
    command: --syncmode "full" --networkid "25" --targetgaslimit "4700000" --port 30303 --rpc --rpcport 8545 --rpcaddr "0.0.0.0" --rpccorsdomain "*" --nat=none --verbosity=4 --mine --bootnodes "enode://be18154ff3753dbb46d59efa460d708a8eec1b547a2983b82ab36a50716e547ed0ca56f97ef625e469b2b752f3db07e1d85952bf87ba328f947a88613ffce755@172.25.0.101:30301" --etherbase "0x60afa8f21f3dba79f3dc9708bc890056c286e7a4" --unlock "0x60afa8f21f3dba79f3dc9708bc890056c286e7a4" --password "/root/.naka/password.txt"

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
