version: '3.7'

services:
  bootnode:
    hostname: bootnode
    container_name: bootnode
    build:
      context: .
      dockerfile: ./docker/bootnode/Dockerfile
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101
    ports:
      - 30301:30301/udp

  testnet-node1:
    hostname: testnet-node1
    container_name: testnet-node1
    depends_on:
      - bootnode
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        PRIVATE_KEY: "60fbbf711c6fcdc50e39a98116a2240330c393a5f3df2f05b72dcbe0857bdc3b" # ONLY FOR DEV
        PASSWORD: "naka" # ONLY FOR DEV
    environment:
        ADDRESS: "0x8102c0ecece895b8fefbddf42b95b7a20925b0c8"
        BOOTNODE_ID: "64b6b3687e748673f192c4967719677ef90e67083435364a85e714e870d343b93ebe8561cdff9d347db86af12aee490f9a2b012e4b80dc31e767b871fe6b7ea5"
        BOOTNODE_IP: "172.25.0.101"
    networks:
      chainnet: 
        ipv4_address: 172.25.0.102
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - node1-testnet-data:/root/.naka:rw
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    
  testnet-node2:
    hostname: testnet-node2
    container_name: testnet-node2
    depends_on:
      - bootnode
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        PRIVATE_KEY: "c1678e3589a49ed370d0764aafe20d061cffb5d6ec9ff2676285135f5bc96d4d" # ONLY FOR DEV
        PASSWORD: "naka" # ONLY FOR DEV
    environment:
        ADDRESS: "0x60afa8f21f3dba79f3dc9708bc890056c286e7a4"
        BOOTNODE_ID: "64b6b3687e748673f192c4967719677ef90e67083435364a85e714e870d343b93ebe8561cdff9d347db86af12aee490f9a2b012e4b80dc31e767b871fe6b7ea5"
        BOOTNODE_IP: "172.25.0.101"
    networks:
      chainnet: 
        ipv4_address: 172.25.0.103
    ports:
      - 8546:8545
      - 30304:30303
    volumes:
      - node2-testnet-data:/root/.naka:rw
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  node1-testnet-data:
  node2-testnet-data:
