version: '3.7'

services:
  client-testnet:
    image: nakachain/go-naka:v1.5.0
    build:
      context: ../../../
      dockerfile: ./node-client/Dockerfile
      args:
        STATIC_NODE_PATH: "./testnet/static-nodes.json"
        GENESIS_PATH: "./testnet/genesis.json"
        EXPOSED_PORTS: "8545 8546 30303"
        BOOTNODES: ${BOOTNODES}
        CHAIN_ID: ${CHAIN_ID}
    restart: on-failure
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - ${HOST_DATA_DIR}:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
