version: '3.7'

services:
  client-testnet:
    image: nakachain/client-testnet:v1.5.0
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        failure_action: rollback
    ports:
      - 9545:8545
      - 9546:8546
      - 40303:30303
    volumes:
      - /home/ubuntu/.naka/testnet:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-size: "400m"
        max-file: "10"
