version: '3.7'

services:
  client-testnet:
    image: nakachain/go-naka:v1.5.0
    build:
      context: ../../../
      dockerfile: ./docker/dockerfiles/Dockerfile.client
      args:
        GENESIS_PATH: ./metadata/testnet/genesis.json
        STATIC_NODE_PATH: ./metadata/testnet/static-nodes.json
        EXPOSED_PORTS: "9545 9546 40303"
        BOOTNODES: ${BOOTNODES}
        CHAIN_ID: ${CHAIN_ID}
    restart: on-failure
    ports:
      - 9545:8545
      - 9546:8546
      - 40303:30303
    volumes:
      - ${HOST_DATA_DIR}:/root/.ethereum
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
