version: '3.7'

services:
  mainnet-client:
    hostname: mainnet-client
    container_name: mainnet-client
    build:
      context: ../
      dockerfile: ./client/Dockerfile
      args:
        GENESIS_PATH: "./mainnet/setup/genesis.json"
        INIT_GENESIS_PATH: "./mainnet/setup/init-genesis.sh"
        EXPOSED_PORTS: "8545 8546 30303"
    environment:
      CHAIN_ID: 250
      BOOTNODE_ID: "29808ed7af11bc46b38b9eab91db47ec40e4733fdc7684183655e2ed2a262676ce5bed031fb79750035f229b0d4288cdc3ead13b777704535aabedad2d4ff8b5"
      BOOTNODE_IP: "52.194.161.36:30301"
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    volumes:
      - mainnet-client-data:/root/.naka:rw
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

volumes:
  mainnet-client-data:
