version: '3.7'

services:
  bootnode:
    hostname: bootnode
    container_name: bootnode
    build:
      context: ../
      dockerfile: ./bootnode/Dockerfile
      args:
        BOOTKEY_PATH: "./mainnet/setup/boot.key"
    networks:
      chainnet: 
        ipv4_address: 172.25.0.101
    ports:
      - 30301:30301

  mainnet-node1:
    hostname: mainnet-node1
    container_name: mainnet-node1
    depends_on:
      - bootnode
    build:
      context: ../
      dockerfile: ./node/Dockerfile
      args:
        PRIVATE_KEY: "60fbbf711c6fcdc50e39a98116a2240330c393a5f3df2f05b72dcbe0857bdc3b" # ONLY FOR DEV
        PASSWORD: "naka" # ONLY FOR DEV
    environment:
        ADDRESS: "0x8102c0ecece895b8fefbddf42b95b7a20925b0c8"
        BOOTNODE_ID: "29808ed7af11bc46b38b9eab91db47ec40e4733fdc7684183655e2ed2a262676ce5bed031fb79750035f229b0d4288cdc3ead13b777704535aabedad2d4ff8b5"
        BOOTNODE_IP: "172.25.0.101"
    networks:
      chainnet: 
        ipv4_address: 172.25.0.102
    ports:
      - 8545:8545
      - 30303:30303
    volumes:
      - mainnet-node1-data:/root/.naka:rw
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"
    
  mainnet-node2:
    hostname: mainnet-node2
    container_name: mainnet-node2
    depends_on:
      - bootnode
    build:
      context: ../
      dockerfile: ./node/Dockerfile
      args:
        PRIVATE_KEY: "c1678e3589a49ed370d0764aafe20d061cffb5d6ec9ff2676285135f5bc96d4d" # ONLY FOR DEV
        PASSWORD: "naka" # ONLY FOR DEV
    environment:
        ADDRESS: "0x60afa8f21f3dba79f3dc9708bc890056c286e7a4"
        BOOTNODE_ID: "29808ed7af11bc46b38b9eab91db47ec40e4733fdc7684183655e2ed2a262676ce5bed031fb79750035f229b0d4288cdc3ead13b777704535aabedad2d4ff8b5"
        BOOTNODE_IP: "172.25.0.101"
    networks:
      chainnet: 
        ipv4_address: 172.25.0.103
    ports:
      - 8546:8545
      - 30304:30303
    volumes:
      - mainnet-node2-data:/root/.naka:rw
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "10"

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  mainnet-node1-data:
  mainnet-node2-data:
