FROM nakachain/go-naka

# RUN adduser -u 1000 -D server
# USER server
# RUN id

# RUN mkdir ~/.naka && chown -R server:server ~/.naka
RUN ls -lah
RUN geth --datadir /root/.naka init /root/.naka/genesis.json
